#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2022

#---------------------------------#
#  Custom Build Script            #
#---------------------------------#
build: off
test: off

build_script:
- powershell .\bootstrap.ps1 -buildNumber %APPVEYOR_BUILD_NUMBER% -branch "%APPVEYOR_REPO_BRANCH%" -buildPath "%APPVEYOR_BUILD_FOLDER%" -gitHubApiKey "%GitHubAPIKey%" -nuGetApiKey "%NuGetAPIKey%"

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Allowed list
  only:
    - main

# GitHub releases create tags, skip builds on tags
skip_tags: true