#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2022

#---------------------------------#
#  Custom Build Script            #
#---------------------------------#
build: off
test: off

build_script:
- powershell .\bootstrap.ps1 -buildNumber %APPVEYOR_BUILD_NUMBER% -branch "%APPVEYOR_REPO_BRANCH%" -buildPath "%APPVEYOR_BUILD_FOLDER%"

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Allowed list
  only:
    - main
    - develop
    - /release/.*/
    - /hotfix/.*/

artifacts:
  - path: '**/artifacts/*.nupkg'
    name: NuGet Packages