version: 2.1
orbs:
  win: circleci/windows@5.0
jobs:
  build-test-deploy:
    executor: win/server-2022
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run:
          name: Build
          command: ./bootstrap.ps1 $env:CIRCLE_BUILD_NUM
workflows:
  build-test-deploy:
    jobs:
      - build-test-deploy